# SITE CONFIGURATION
title: 豆鸽的博客 # your site title
author: TernuraR # You :P
description: > # Meta description of Homepage
  一只力图记录自己飞行轨迹的鸽。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://TernuraR.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: 豆鸽
  links:
  #  - https://twitter.com/BenBalter
  #  - https://www.facebook.com/ben.balter
  #  - https://www.linkedin.com/in/BenBalter
  #  - https://plus.google.com/+BenBalter
    - https://github.com/TernuraR
  #  - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  I hear and I forget, I read and I remember, I write and I understand.

hero_img: posts/sea_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: 12140813hzr@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  TernuraR # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: https-ternurar-github-io # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
#theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
